=== PeterPerhac/get-nino-api/public/api/conf/1.0/schema/register-nino.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "POST Account Creation Request Schema",
  "description": "JSON representation of POST Account Creation Request Payload",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "nino": {
      "description": "The primary identifier for the account creation request with suffix",
      "$ref": "#/definitions/nino"
    },
    "gender": {
      "description": "The individual's gender",
      "type": "string",
      "enum": [
        "MALE",
        "FEMALE",
        "NOT-KNOWN"
      ]
    },
    "entryDate": {
      "description": "The date of entry into the account registration process",
      "$ref": "#/definitions/date"
    },
    "birthDate": {
      "description": "The individual's date of birth",
      "$ref": "#/definitions/date"
    },
    "birthDateVerification": {
      "description": "The verification level relating to individual's date of birth",
      "type": "string",
      "enum": [
        "UNVERIFIED",
        "VERIFIED",
        "NOT KNOWN",
        "COEG CONFIRMED"
      ]
    },
    "officeNumber": {
      "description": "Related DWP Office Number",
      "type": "string",
      "pattern": "^([0-9]{1,6})$"
    },
    "contactNumber": {
      "description": "The individual's contact number",
      "$ref": "#/definitions/contactNumber"
    },
    "nationalityCode": {
      "description": "The individual's nationality",
      "$ref": "#/definitions/countryCode"
    },
    "names": {
      "description": "Details of the individual's current valid names",
      "type": "array",
      "minItems": 1,
      "maxItems": 2,
      "uniqueItems": true,
      "items": {
        "description": "One of an individual's currently valid names.",
        "$ref": "#/definitions/name"
      }
    },
    "historicNames": {
      "type": "array",
      "minItems": 1,
      "maxItems": 5,
      "additionalItems": false,
      "uniqueItems": true,
      "items": {
        "description": "A list of historic name details for the individual",
        "$ref": "#/definitions/name"
      }
    },
    "addresses": {
      "description": "Details of the individual's currently valid addresses",
      "type": "array",
      "minItems": 1,
      "maxItems": 2,
      "uniqueItems": true,
      "items": {
        "description": "Details of one of an individual's current valid addresses",
        "$ref": "#/definitions/address"
      }
    },
    "historicAddresses": {
      "type": "array",
      "minItems": 1,
      "maxItems": 5,
      "additionalItems": false,
      "uniqueItems": true,
      "items": {
        "description": "A list of historic address details for the individual",
        "$ref": "#/definitions/address"
      }
    },
    "marriages": {
      "type": "array",
      "minItems": 1,
      "maxItems": 5,
      "additionalItems": false,
      "uniqueItems": true,
      "items": {
        "description": "A list of marriage details for the individual",
        "$ref": "#/definitions/marriage"
      }
    },
    "originData": {
      "description": "The individual's origin details",
      "$ref": "#/definitions/origins"
    },
    "priorResidency": {
      "type": "array",
      "minItems": 1,
      "maxItems": 5,
      "additionalItems": false,
      "uniqueItems": true,
      "items": {
        "description": "A list of prior UK residency periods (longer than 30 days)",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "priorStartDate": {
            "description": "The prior UK residency period start date",
            "$ref": "#/definitions/date"
          },
          "priorEndDate": {
            "description": "The prior UK residency period end date",
            "$ref": "#/definitions/date"
          }
        }
      }
    }
  },
  "required": [
    "nino",
    "gender",
    "entryDate",
    "birthDate",
    "officeNumber",
    "names",
    "addresses"
  ],
  "definitions": {
    "name": {
      "description": "Multi-Use Name Object",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "nameType": {
          "description": "Type of name provided",
          "type": "string",
          "enum": [
            "REGISTERED",
            "ALIAS"
          ]
        },
        "title": {
          "description": "Name Title String",
          "type": "string",
          "enum": [
            "NOT KNOWN",
            "MR",
            "MRS",
            "MISS",
            "MS",
            "DR",
            "REV"
          ]
        },
        "forename": {
          "description": "The individual's primary forename string",
          "$ref": "#/definitions/nameElement"
        },
        "secondForename": {
          "description": "The individual's secondary forename string",
          "$ref": "#/definitions/nameElement"
        },
        "surname": {
          "description": "The individual's surname string",
          "$ref": "#/definitions/nameElement"
        },
        "startDate": {
          "description": "The individual's name record start date",
          "$ref": "#/definitions/date"
        },
        "endDate": {
          "description": "The individual's name record end date",
          "$ref": "#/definitions/date"
        }
      },
      "required": [
        "nameType",
        "surname"
      ]
    },
    "address": {
      "description": "Multi-Use Address Object",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "addressType": {
          "description": "The type of address provided",
          "type": "string",
          "enum": [
            "RESIDENTIAL",
            "CORRESPONDENCE"
          ]
        },
        "line1": {
          "description": "The first line of the address",
          "$ref": "#/definitions/addressLine"
        },
        "line2": {
          "description": "The second line of the address",
          "$ref": "#/definitions/addressLine"
        },
        "line3": {
          "description": "The third line of the address",
          "$ref": "#/definitions/addressLine"
        },
        "line4": {
          "description": "The fourth line of the address",
          "$ref": "#/definitions/addressLine"
        },
        "line5": {
          "description": "The fifth line of the address",
          "$ref": "#/definitions/addressLine"
        },
        "postcode": {
          "description": "The address postcode - this will be mandatory if the countryCode field has the value 'GBR', and optional otherwise",
          "$ref": "#/definitions/postcode"
        },
        "countryCode": {
          "description": "The address country code",
          "$ref": "#/definitions/countryCode"
        },
        "startDate": {
          "description": "The individual's address record start date",
          "$ref": "#/definitions/date"
        },
        "endDate": {
          "description": "The individual's address record end date",
          "$ref": "#/definitions/date"
        }
      },
      "required": [
        "addressType",
        "line1",
        "countryCode"
      ]
    },
    "marriage": {
      "description": "Multi-Use Marriage Object",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "maritalStatus": {
          "description": "Marital status enumeration",
          "type": "string",
          "enum": [
            "MARRIAGE-TERMINATED",
            "MARRIAGE-ANNULLED",
            "VOID",
            "DIVORCED",
            "WIDOWED",
            "MARRIED",
            "SINGLE",
            "CIVIL-PARTNERSHIP",
            "CIVIL-PARTNERSHIP-DISSOLVED",
            "SURVIVING-CIVIL-PARTNERSHIP",
            "CIVIL-PARTNERSHIP-TERMINATED",
            "CIVIL-PARTNERSHIP-ANNULLED"
          ]
        },
        "startDate": {
          "description": "The marriage record start date",
          "$ref": "#/definitions/date"
        },
        "endDate": {
          "description": "The marriage record end date",
          "$ref": "#/definitions/date"
        },
        "partnerNino": {
          "description": "The spouse's primary account identifier",
          "$ref": "#/definitions/nino"
        },
        "birthDate": {
          "description": "The spouse's date of birth",
          "$ref": "#/definitions/date"
        },
        "forename": {
          "description": "The spouse's primary forename string",
          "$ref": "#/definitions/nameElement"
        },
        "surname": {
          "description": "The spouse's surname string",
          "$ref": "#/definitions/nameElement"
        }
      },
      "required": [
        "partnerNino",
        "birthDate"
      ]
    },
    "origins": {
      "description": "Individual Origins Object",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "birthTown": {
          "description": "The individual's birth town",
          "$ref": "#/definitions/originsElement"
        },
        "birthProvince": {
          "description": "The individual's birth province",
          "$ref": "#/definitions/originsElement"
        },
        "birthCountryCode": {
          "description": "The individual's birth country code",
          "$ref": "#/definitions/countryCode"
        },
        "birthSurname": {
          "description": "The individual's surname at birth",
          "$ref": "#/definitions/nameElement"
        },
        "maternalForename": {
          "description": "The individual's maternal parent's forename",
          "$ref": "#/definitions/nameElement"
        },
        "maternalSurname": {
          "description": "The individual's maternal parent's surname",
          "$ref": "#/definitions/nameElement"
        },
        "paternalForename": {
          "description": "The individual's paternal parent's forename",
          "$ref": "#/definitions/nameElement"
        },
        "paternalSurname": {
          "description": "The individual's paternal parent's surname",
          "$ref": "#/definitions/nameElement"
        },
        "foreignSocialSecurity": {
          "description": "The individual's previous, non-UK social security reference",
          "type": "string",
          "pattern": "^(?=.{1,35}$)([A-Z]([-'.&\\/ ]{0,1}[A-Za-z]+)*[A-Za-z]?)$"
        },
        "lastEUAddress": {
          "description": "The individual's last non-UK address details",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "line1": {
              "description": "The first line of the address",
              "$ref": "#/definitions/addressLine"
            },
            "line2": {
              "description": "The second line of the address",
              "$ref": "#/definitions/addressLine"
            },
            "line3": {
              "description": "The third line of the address",
              "$ref": "#/definitions/addressLine"
            },
            "line4": {
              "description": "The fourth line of the address",
              "$ref": "#/definitions/addressLine"
            },
            "line5": {
              "description": "The fifth line of the address",
              "$ref": "#/definitions/addressLine"
            }
          }
        }
      }
    },
    "nino": {
      "description": "Primary Account Identifier (with enforced trailing suffix character)",
      "type": "string",
      "pattern": "^((?!(BG|GB|KN|NK|NT|TN|ZZ)|(D|F|I|Q|U|V)[A-Z]|[A-Z](D|F|I|O|Q|U|V))[A-Z]{2})[0-9]{6}[A-D]$"
    },
    "date": {
      "description": "Common Date Format. ",
      "type": "string",
      "pattern": "^([0-2][0-9]|(3)[0-1])(\\-)(((0)[0-9])|((1)[0-2]))(\\-)\\d{4}$"
    },
    "contactNumber": {
      "description": "Common Simple Contact Number Format",
      "type": "string",
      "pattern": "^([+]{0,1}[0-9 ]{1,70}[0-9])$"
    },
    "nameElement": {
      "description": "Common Name Element Format",
      "type": "string",
      "pattern": "^(?=.{1,99}$)([A-Z]([-'. ]{0,1}[A-Za-z ]+)*[A-Za-z]?)$"
    },
    "addressLine": {
      "description": "Common Address Line Format",
      "type": "string",
      "pattern": "^(?=.{1,35}$)([A-Za-z0-9]([-'.& ]?[A-Za-z0-9 ]+)*)$"
    },
    "postcode": {
      "description": "Common postal code type including older british forces postal office codes",
      "type": "string",
      "pattern": "^(([A-Z]{1,2})|([A-Z]{1,2}[0-9][0-9A-Z]?)|([A-Z]{1,2}[0-9][0-9A-Z]? ?[0-9])|([A-Z]{1,2}[0-9][0-9A-Z]? ?[0-9][A-Z]{2})|(BFPO ?[0-9]{1,4}))$"
    },
    "originsElement": {
      "description": "Origins Address Element",
      "type": "string",
      "pattern": "^(?=.{1,35}$)([A-Z]([-'.&\\/ ]{0,1}[A-Za-z]+)*[A-Za-z]?)$"
    },
    "countryCode": {
      "description": "ISO 3166-1 alpha-3 Country Codes",
      "type": "string",
      "pattern": "^[A-Z]{3}$"
    }
  }
}

=== PeterPerhac/get-nino-api/public/api/conf/1.0/examples/register/register-max-post.json
{
  "nino": "GW629902A",
  "gender": "MALE",
  "entryDate": "10-10-2020",
  "birthDate": "10-10-2020",
  "birthDateVerification": "VERIFIED",
  "officeNumber": "1234",
  "contactNumber": "1234567890",
  "nationalityCode": "GBR",
  "names": [
    {
      "nameType": "REGISTERED",
      "title": "MR",
      "forename": "AForename",
      "secondForename": "NotSure",
      "surname": "ASurname",
      "startDate": "10-10-2020",
      "endDate": "10-10-2020"
    }
  ],
  "historicNames": [
    {
      "nameType": "REGISTERED",
      "title": "MRS",
      "forename": "AForename",
      "secondForename": "NotSure",
      "surname": "ASurname",
      "startDate": "10-10-2020",
      "endDate": "10-10-2020"
    },
    {
      "nameType": "REGISTERED",
      "title": "MISS",
      "forename": "AForename",
      "secondForename": "NotSure",
      "surname": "ASurname",
      "startDate": "10-10-2020",
      "endDate": "10-10-2020"
    }
  ],
  "addresses": [
    {
      "addressType": "RESIDENTIAL",
      "line1": "4 AStreetName",
      "line2": "Some",
      "line3": "Old",
      "line4": "Place",
      "line5": "ItsTheFinalLine",
      "postcode": "AA1 1AA",
      "countryCode": "GBR",
      "startDate": "10-10-2020",
      "endDate": "10-10-2020"
    }
  ],
  "historicAddresses": [
    {
      "addressType": "RESIDENTIAL",
      "line1": "1 AStreetName",
      "line2": "Some",
      "line3": "Old",
      "line4": "Place",
      "line5": "ItsTheFinalLine",
      "postcode": "AA1 1AA",
      "countryCode": "GBR",
      "startDate": "10-10-2020",
      "endDate": "10-10-2020"
    },
    {
      "addressType": "RESIDENTIAL",
      "line1": "4 AStreetName",
      "line2": "Some",
      "line3": "Old",
      "line4": "Place",
      "line5": "ItsTheFinalLine",
      "postcode": "AA1 1AA",
      "countryCode": "GBR",
      "startDate": "10-10-2020",
      "endDate": "10-10-2020"
    }
  ],
  "originData": {
    "birthTown": "ATown",
    "birthProvince": "SomeProvince",
    "birthCountryCode": "GBR",
    "birthSurname": "ASurname",
    "maternalForename": "MotherForename",
    "maternalSurname": "AnotherSurname",
    "paternalForename": "AForename",
    "paternalSurname": "ASurname",
    "foreignSocialSecurity": "SomeSocialSecurityNumber",
    "lastEUAddress": {
      "line1": "4 AStreetName",
      "line2": "Some",
      "line3": "Old",
      "line4": "Place",
      "line5": "ItsTheFinalLine"
    }
  },
  "priorResidency": [
    {
      "priorStartDate": "10-10-2020",
      "priorEndDate": "10-10-2020"
    },
    {
      "priorStartDate": "10-11-2020",
      "priorEndDate": "10-11-2020"
    }
  ]
}

=== PeterPerhac/get-nino-api/public/api/conf/1.0/examples/register/register-min-post.json
{
  "nino": "GW629902A",
  "gender": "MALE",
  "entryDate": "10-10-2020",
  "birthDate": "10-10-2020",
  "officeNumber": "1234",
  "names": [
    {
      "nameType": "REGISTERED",
      "surname": "ASurname"
    }
  ],
  "addresses": [
    {
      "addressType": "RESIDENTIAL",
      "line1": "4 AStreetName",
      "countryCode": "NGA"
    }
  ]
}
